- id: living_room_motion_on
  alias: Living Room Motion On
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'on'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.living_room_occupied
  mode: single

- id: living_room_motion_off
  alias: Living Room Motion Off
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'off'
    for:
      minutes: 10
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.living_room_occupied
  mode: single

- id: living_room_occupied
  alias: Living Room Occupied
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.living_room_occupied
    to: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.zooz_zen25_s2_double_plug_switch
  mode: single

- id: living_room_unoccupied
  alias: Living Room Unoccupied
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.living_room_occupied
    to: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.zooz_zen25_s2_double_plug_switch
  mode: single
