- id: living_room_motion
  alias: 'Living Room Motion'
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_motion
    from: 'off'
    to: 'on'
  action:
    - service: timer.start
      entity_id: timer.living_room_motion
    - service: input_boolean.turn_on
      entity_id: input_boolean.living_room_occupied
  mode: single
