- id: set_default_theme
  alias: Set default them on startup
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  condition: []
  action:
    service: frontend.set_theme
    data:
      name: ios-dark-mode-light-green

- id: living_room_motion
  alias: Living Room Motion
  description: ''
  use_blueprint:
    path: homeassistant/motion_switch.yaml
    input:
      motion_entity: binary_sensor.living_room_motion
      switch_target:
        entity_id: switch.living_room_right_plug_switch
      no_motion_wait: 600

- id: living_room_motion_on
  alias: Living Room Motion On
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion
      to: "on"
  condition: []
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.living_room_occupied
  mode: single

- id: living_room_motion_off
  alias: Living Room Motion Off
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion
      to: "off"
      for:
        minutes: 10
  condition: []
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.living_room_occupied
  mode: single

- id: living_room_occupied
  alias: Living Room Occupied
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.living_room_occupied
      to: "on"
  condition: []
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_left_plug_switch
  mode: single

- id: living_room_unoccupied
  alias: Living Room Unoccupied
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.living_room_occupied
      to: "off"
  condition: []
  action:
    - service: switch.turn_off
      entity_id: switch.living_room_left_plug_switch
  mode: single

- id: master_bathroom_high_humidity
  alias: Master Bathroom High Humidity
  trigger:
    - above: 60
      entity_id: sensor.logans_room_sensor_relative_humidity
      platform: numeric_state
  condition: []
  action:
    service: notify.mobile_app_craigs_iphone
    data:
      message: Master bathroom high humidity
  mode: single

- id: master_bathroom_low_humidity
  alias: Master Bathroom Low Humidity
  trigger:
    - below: 58
      entity_id: sensor.logans_room_sensor_relative_humidity
      platform: numeric_state
  condition: []
  action:
    service: notify.mobile_app_craigs_iphone
    data:
      message: Master bathroom low humidity
  mode: single

- id: occupancy_home
  alias: Set Occupancy To Home
  description: ""
  trigger:
    - platform: state
      entity_id: input_select.occupancy
      to: Home
  condition: []
  action:
    service: script.turn_on
    data:
      entity_id: script.occupancy_home
  mode: single

- id: occupancy_away
  alias: Set Occupancy To Away
  description: ""
  trigger:
    - platform: state
      entity_id: input_select.occupancy
      to: Away
  condition: []
  action:
    service: script.turn_on
    data:
      entity_id: script.occupancy_away
  mode: single

- id: occupancy_sleep
  alias: Set Occupancy To Sleep
  description: ""
  trigger:
    - platform: state
      entity_id: input_select.occupancy
      to: Sleep
  condition: []
  action:
    service: script.turn_on
    data:
      entity_id: script.occupancy_sleep
  mode: single

- id: occupancy_vacation
  alias: Set Occupancy To Vacation
  description: ""
  trigger:
    - platform: state
      entity_id: input_select.occupancy
      to: Vacation
  condition: []
  action:
    service: script.turn_on
    data:
      entity_id: script.occupancy_vacation
  mode: single
