- id: set_default_theme
  alias: Set default them on startup
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  condition: []
  action:
    service: frontend.set_theme
    data:
      # name: ios-dark-mode-light-green
      name: iOS Dark Mode

- id: living_room_motion
  alias: Living Room Motion
  description: ''
  use_blueprint:
    path: homeassistant/motion_switch.yaml
    input:
      motion_entity: binary_sensor.living_room_motion
      switch_target:
        entity_id: switch.living_room_right_plug_switch
      no_motion_wait: 600

# - id: master_bathroom_high_humidity
#   alias: Master Bathroom High Humidity
#   trigger:
#   - above: 5
#     entity_id: sensor.master_bathroom_humidity_delta
#     platform: numeric_state
#   condition: []
#   action:
#     service: notify.mobile_app_craigs_iphone
#     data:
#       message: Master bathroom high delta humidity
#   mode: single

# - id: master_bathroom_low_humidity
#   alias: Master Bathroom Low Humidity
#   trigger:
#   - below: 5
#     entity_id: sensor.master_bathroom_humidity_delta
#     platform: numeric_state
#   condition: []
#   action:
#     service: notify.mobile_app_craigs_iphone
#     data:
#       message: Master bathroom low delta humidity
#   mode: single

# - id: master_bathroom_humidity_rising
#   alias: Master Bathroom Humidity Rising
#   description: ''
#   trigger:
#   - platform: state
#     entity_id: binary_sensor.master_bathroom_humidity_rising
#     to: 'on'
#   condition: []
#   action:
#     service: notify.mobile_app_craigs_iphone
#     data:
#       message: Master bathroom humidity rising
#   mode: single

# - id: master_bathroom_humidity_falling
#   alias: Master Bathroom Humidity Falling
#   description: ''
#   trigger:
#   - platform: state
#     entity_id: binary_sensor.master_bathroom_humidity_falling
#     to: 'on'
#   condition: []
#   action:
#     service: notify.mobile_app_craigs_iphone
#     data:
#       message: Master bathroom humidity falling
#   mode: single

- id: occupancy_home
  alias: Set Occupancy To Home
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.occupancy
    to: Home
  condition: []
  action:
    service: script.turn_on
    data:
      entity_id: script.occupancy_home
  mode: single

- id: occupancy_away
  alias: Set Occupancy To Away
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.occupancy
    to: Away
  condition: []
  action:
    service: script.turn_on
    data:
      entity_id: script.occupancy_away
  mode: single

- id: occupancy_sleep
  alias: Set Occupancy To Sleep
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.occupancy
    to: Sleep
  condition: []
  action:
    service: script.turn_on
    data:
      entity_id: script.occupancy_sleep
  mode: single

- id: occupancy_vacation
  alias: Set Occupancy To Vacation
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.occupancy
    to: Vacation
  condition: []
  action:
    service: script.turn_on
    data:
      entity_id: script.occupancy_vacation
  mode: single

# - id: logan_sleep
#   alias: Set Logan to sleep
#   description: ''
#   trigger:
#   - platform: state
#     entity_id: input_boolean.logan_sleep
#     from: 'off'
#     to: 'on'
#   condition: []
#   action:
#     service: script.turn_on
#     data:
#       entity_id: script.good_night_logan
#   mode: single

# - id: logan_awake
#   alias: Set Logan to awake
#   description: ''
#   trigger:
#   - platform: state
#     entity_id: input_boolean.logan_sleep
#     from: 'on'
#     to: 'off'
#   condition: []
#   action:
#     service: script.turn_on
#     data:
#       entity_id: script.good_morning_logan
#   mode: single

- id: front_door_tag_scan
  alias: Front Door Tag Scan
  description: ''
  trigger:
  - platform: tag
    tag_id: front_door_tag
  condition: []
  action:
    service: switch.toggle
    data:
      entity_id: switch.living_room_right_plug_switch
  mode: single

- id: christmas_tag_scan
  alias: Christmas Tag Scan
  description: ''
  trigger:
  - platform: tag
    tag_id: christmas
  condition: []
  action:
    service: switch.toggle
    data:
      entity_id: switch.christmas
  mode: single
