
- id: '1607301877677'
  alias: aaa motion detected
  initial_state: false
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.aaa_occupied
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: timer.start
    data: {}
    entity_id: timer.aaa_home_time
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.aaa_home
  mode: single

- id: living_room_motion
  alias: 'Living Room Motion'
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_motion
    from: 'off'
    to: 'on'
  action:
    - service: timer.start
      entity_id: timer.living_room_motion
    - service: input_boolean.turn_on
      entity_id: input_boolean.aaa_home
  mode: single
