- platform: template
  sensors:
    living_room_motion:
      friendly_name: "Living Room Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.zooz_zse40_4_in_1_sensor_burglar', '8') }}"
