- platform: template
  sensors:
    aaa_sensor:
      friendly_name: "AAA Zooz Motion Sensor"
      device_class: motion
      value_template: "{{ is_state('sensor.zooz_zse40_4_in_1_sensor_burglar', '8') }}"

