## This configuration.yaml file is provided by the Home Assistant Core iocage-jail for FreeNAS
# https://www.home-assistant.io/docs/configuration

homeassistant:
  # https://www.home-assistant.io/docs/configuration/customizing-devices/
  customize: !include customize.yaml
  # https://www.home-assistant.io/docs/configuration/packages/#create-a-packages-folder
  packages: !include_dir_named packages

# https://www.home-assistant.io/integrations/http/#ip_ban_enabled
http:
  ip_ban_enabled: False
  login_attempts_threshold: 5

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info

## Configure a default setup of Home Assistant Core (frontend, api, etc)
# https://www.home-assistant.io/integrations/default_config
default_config:

# Lovelace UI elements
lovelace:
  mode: yaml
  resources:
    - url: /local/community/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /local/custom-lovelace/weather-card/weather-card.js
      type: module

# Frontend stuff
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

# InfluxDB
# influxdb:
#   host: !secret influx_host
#   username: !secret influx_user
#   password: !secret influx_password
#   include:
#     entities:
#       - sensor.living_room_sensor_temperature
#       - sensor.living_room_sensor_relative_humidity
#       - sensor.living_room_sensor_luminance
#       - binary_sensor.living_room_motion
#       - sensor.logans_room_sensor_temperature
#       - sensor.logans_room_sensor_relative_humidity
#       - sensor.logans_room_sensor_luminance
#       - binary_sensor.logans_room_motion
#       - binary_sensor.day
#       - binary_sensor.night

homekit: !include homekit.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
timer: !include  timers.yaml
input_boolean: !include input_booleans.yaml
