## This configuration.yaml file is provided by the Home Assistant Core iocage-jail for FreeNAS
# https://www.home-assistant.io/docs/configuration

homeassistant:
  # https://www.home-assistant.io/docs/configuration/customizing-devices/
  customize: !include customize.yaml
  # https://www.home-assistant.io/docs/configuration/packages/#create-a-packages-folder
  packages: !include_dir_named packages

# https://www.home-assistant.io/integrations/http/#ip_ban_enabled
http:
  ip_ban_enabled: False
  login_attempts_threshold: 5

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info

## Configure a default setup of Home Assistant Core (frontend, api, etc)
# https://www.home-assistant.io/integrations/default_config
default_config:

ffmpeg:
  ffmpeg_bin: /usr/local/bin/ffmpeg

# Frontend stuff
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

zone: !include zones.yaml
lovelace: !include lovelace.yaml
influxdb: !include influxdb.yaml
homekit: !include homekit.yaml
cloud: !include cloud.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
timer: !include  timers.yaml
input_boolean: !include input_booleans.yaml
input_select: !include input_selects.yaml
switch: !include switches.yaml
