- platform: template
  switches:
    logans_xbox:
      friendly_name: Logans Xbox
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Xbox') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "Xbox"
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
