- platform: template
  switches:
    logans_xbox:
      friendly_name: Logans Xbox
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Xbox') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "Xbox"
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub

    logans_tv:
      friendly_name: Logans TV
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'TV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "TV"
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub

    logan_sleep:
      friendly_name: Logan Sleep
      value_template: "{{ is_state('input_boolean.logan_sleep', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.good_night_logan
      turn_off:
        service: script.turn_on
        entity_id: script.good_morning_logan 

    christmas:
      friendly_name: Christmas
      value_template: "{{ is_state('input_boolean.christmas', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_christmas
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_christmas

    home:
      friendly_name: Home
      value_template: "{{ is_state('input_select.occupancy', 'Home') }}"
      turn_on:
        service: input_select.select_option
        data:
            entity_id: input_select.occupancy
            option: Home
      turn_off:
        service: input_select.select_option
        data:
            entity_id: input_select.occupancy
            option: Home

    away:
      friendly_name: Away
      value_template: "{{ is_state('input_select.occupancy', 'Away') }}"
      turn_on:
        service: input_select.select_option
        data:
            entity_id: input_select.occupancy
            option: Away
      turn_off:
        service: input_select.select_option
        data:
            entity_id: input_select.occupancy
            option: Away

    sleep:
      friendly_name: Sleep
      value_template: "{{ is_state('input_select.occupancy', 'Sleep') }}"
      turn_on:
        service: input_select.select_option
        data:
            entity_id: input_select.occupancy
            option: Sleep
      turn_off:
        service: input_select.select_option
        data:
            entity_id: input_select.occupancy
            option: Sleep

    vacation:
      friendly_name: Vacation
      value_template: "{{ is_state('input_select.occupancy', 'Vacation') }}"
      turn_on:
        service: input_select.select_option
        data:
            entity_id: input_select.occupancy
            option: Vacation
      turn_off:
        service: input_select.select_option
        data:
            entity_id: input_select.occupancy
            option: Vacation

            