title: Home
views:
  - title: Main Floor
    path: main-floor
    panel: false
    badges: []
    cards:
      - type: picture-elements
        elements:
          #
          # Labels outside diagram
          #
          - type: state-label
            entity: sensor.speedtest_download
            suffix: ' Down'
            style:
              top: 0%
              left: 0%
              color: black
              transform: 'translate(0%, 0%)'
          
          #
          # Kitchen
          #
          - type: state-label
            entity: sensor.speedtest_download
            suffix: ' Down'
            style:
              top: 0%
              left: 0%
              color: black
              transform: 'translate(0%, 0%)'
          - type: state-icon
            entity: vacuum.robi
            style:
              top: 20%
              right: 4%
              transform: rotate(270deg)
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              top: 26%
              right: 9%
              transform: 'translate(0%, 0)'
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              top: 37%
              right: 11%
              transform: 'translate(0%, 0)'
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              top: 51%
              right: 5%
              transform: 'translate(0%, 0)'
          
          #
          # Living Room
          #
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              top: 32%
              right: 28%
              transform: 'translate(0%, 0)'
          - type: state-label
            entity: sensor.zooz_zse40_4_in_1_sensor_temperature
            style:
              top: 38%
              left: 58%
              color: blue
              transform: 'translate(0%, 0%)'
          - type: state-label
            entity: sensor.zooz_zse40_4_in_1_sensor_relative_humidity
            style:
              top: 41%
              left: 58%
              color: BlueViolet
              transform: 'translate(0%, 0%)'
          - type: state-label
            entity: sensor.zooz_zse40_4_in_1_sensor_luminance
            style:
              top: 44%
              left: 58%
              color: CornflowerBlue
              transform: 'translate(0%, 0%)'
          - type: state-icon
            entity: input_boolean.living_room_occupied
            style:
              top: 33%
              left: 71%
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:pine-tree'
            entity: switch.zooz_zen25_s2_double_plug_switch
            tap_action:
              action: toggle
            style:
              top: 27%
              left: 55%
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:power-plug'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              top: 31%
              left: 55%
              transform: 'translate(0%, 0%)'

          #
          # Outside Cameras
          #
          - type: state-icon
            icon: 'mdi:video'
            entity: camera.robi_cleaning_map
            style:
              top: 37%
              left: 18%
              transform: 'translate(0%, 0%) rotate(180deg)'
          - type: state-icon
            icon: 'mdi:video'
            entity: camera.robi_cleaning_map
            style:
              top: 53%
              left: '-1%'
              transform: 'translate(0%, 0%) rotate(180deg)'
          - type: state-icon
            icon: 'mdi:video'
            entity: camera.robi_cleaning_map
            style:
              top: 67%
              left: '-1%'
              transform: 'translate(0%, 0%) rotate(180deg)'
          - type: state-icon
            icon: 'mdi:video'
            entity: camera.robi_cleaning_map
            style:
              top: 23%
              left: 35%
              transform: 'translate(0%, 0%) rotate(270deg)'
          - type: state-icon
            icon: 'mdi:video'
            entity: camera.robi_cleaning_map
            style:
              top: 23%
              left: 72%
              transform: 'translate(0%, 0%) rotate(270deg)'
          - type: state-icon
            icon: 'mdi:video'
            entity: camera.robi_cleaning_map
            style:
              top: 50%
              right: '-1%'
              transform: 'translate(0%, 0%)'

          #
          # Front Yard
          #
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              bottom: 14%
              left: 37%
              transform: 'translate(0%, 0)'
          - type: state-icon
            icon: 'mdi:walk'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              bottom: 14%
              left: 45%
              transform: 'translate(0%, 0%)'
          - type: state-label
            entity: sensor.zooz_zse40_4_in_1_sensor_temperature
            style:
              bottom: 14%
              left: 25%
              color: blue
              transform: 'translate(0%, 0%)'
          
          #
          # Garage
          #
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              bottom: 31%
              left: 26%
              transform: 'translate(0%, 0)'
          - type: state-icon
            icon: 'mdi:walk'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              bottom: 31%
              left: 33%
              transform: 'translate(0%, 0%)'
          - type: state-label
            entity: sensor.zooz_zse40_4_in_1_sensor_temperature
            style:
              bottom: 39%
              left: 25%
              color: blue
              transform: 'translate(0%, 0%)'

          #
          # Logans Room
          #
          - type: state-label
            entity: sensor.zooz_zse40_4_in_1_sensor_temperature
            style:
              bottom: 26%
              left: 66%
              color: blue
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:walk'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              bottom: 23%
              left: 65%
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              bottom: 29%
              left: 68%
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:spotify'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              bottom: 23%
              left: 72%
              transform: 'translate(0%, 0%)'

          #
          # Jocelyns Room
          #
          - type: state-label
            entity: sensor.zooz_zse40_4_in_1_sensor_temperature
            style:
              bottom: 25%
              right: 5%
              color: blue
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:walk'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              bottom: 21%
              right: 13%
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              bottom: 28%
              right: 9%
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:spotify'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              bottom: 21%
              right: 5%
              transform: 'translate(0%, 0%)'

          #
          # Master Bedroom
          #
          - type: state-label
            entity: sensor.zooz_zse40_4_in_1_sensor_temperature
            style:
              top: 28%
              left: 40%
              color: blue
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:walk'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              top: 37%
              left: 38%
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              top: 32%
              left: 42%
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:spotify'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              top: 37%
              left: 45%
              transform: 'translate(0%, 0%)'

          #
          # Master Closet
          #
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              top: 45%
              left: 25%
              transform: 'translate(0%, 0)'

          #
          # Master Bath
          #
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              top: 31%
              left: 25%
              transform: 'translate(0%, 0)'

          #
          # Laundry Room
          #
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              top: 45%
              left: 34%
              transform: 'translate(0%, 0)'

          #
          # Mud Room
          #
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              top: 43%
              left: 44%
              transform: 'translate(0%, 0)'

          #
          # Bathroom
          #
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.zooz_zen25_s2_double_plug_switch_2
            tap_action:
              action: toggle
            style:
              top: 52%
              right: 13%
              transform: 'translate(0%, 0)'
        image:
          http://192.168.1.207:8123/local/main-floor-plan.jpg
  
  - title: Test
    path: test
    badges: []
    cards:
      - type: weather-forecast
        entity: weather.home
        show_forecast: true
      - type: entities
        entities:
          - entity: input_boolean.living_room_occupied
          - entity: sensor.plex_plex_media_server
      - type: sensor
        entity: sensor.zooz_zse40_4_in_1_sensor_temperature
        name: Living Room
        detail: 1
        graph: line
