title: Home2
views:
  - title: Main Floor
    path: main-floor
    panel: false
    icon: mdi:floor-plan
    badges: []
    cards:
      - type: picture-elements
        elements:
          #
          # Labels outside diagram
          #
          # - type: state-label
          #   entity: sensor.speedtest_download
          #   suffix: ' Down'
          #   style:
          #     top: 0%
          #     left: 0%
          #     color: black
          #     transform: 'translate(0%, 0%)'
          
          #
          # Kitchen
          #
          - type: state-icon
            entity: vacuum.robi
            style:
              top: 20%
              right: 4%
              transform: rotate(270deg)
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              top: 26%
              right: 9%
              transform: 'translate(0%, 0)'
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              top: 37%
              right: 11%
              transform: 'translate(0%, 0)'
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              top: 51%
              right: 5%
              transform: 'translate(0%, 0)'
          
          #
          # Living Room
          #
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              top: 32%
              right: 28%
              transform: 'translate(0%, 0)'
          - type: state-label
            entity: sensor.living_room_sensor_temperature
            style:
              top: 38%
              left: 58%
              color: blue
              transform: 'translate(0%, 0%)'
          - type: state-label
            entity: sensor.living_room_sensor_relative_humidity
            style:
              top: 41%
              left: 58%
              color: BlueViolet
              transform: 'translate(0%, 0%)'
          - type: state-label
            entity: sensor.living_room_sensor_luminance
            style:
              top: 44%
              left: 58%
              color: CornflowerBlue
              transform: 'translate(0%, 0%)'
          - type: state-icon
            entity: input_boolean.living_room_occupied
            style:
              top: 33%
              left: 71%
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:pine-tree'
            entity: switch.living_room_left_plug_switch
            tap_action:
              action: toggle
            style:
              top: 27%
              left: 55%
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:power-plug'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              top: 31%
              left: 55%
              transform: 'translate(0%, 0%)'

          #
          # Outside Cameras
          #
          - type: state-icon
            icon: 'mdi:video'
            entity: camera.robi_cleaning_map
            style:
              top: 37%
              left: 18%
              transform: 'translate(0%, 0%) rotate(180deg)'
          - type: state-icon
            icon: 'mdi:video'
            entity: camera.robi_cleaning_map
            style:
              top: 53%
              left: '-1%'
              transform: 'translate(0%, 0%) rotate(180deg)'
          - type: state-icon
            icon: 'mdi:video'
            entity: camera.robi_cleaning_map
            style:
              top: 67%
              left: '-1%'
              transform: 'translate(0%, 0%) rotate(180deg)'
          - type: state-icon
            icon: 'mdi:video'
            entity: camera.robi_cleaning_map
            style:
              top: 23%
              left: 35%
              transform: 'translate(0%, 0%) rotate(270deg)'
          - type: state-icon
            icon: 'mdi:video'
            entity: camera.robi_cleaning_map
            style:
              top: 23%
              left: 72%
              transform: 'translate(0%, 0%) rotate(270deg)'
          - type: state-icon
            icon: 'mdi:video'
            entity: camera.robi_cleaning_map
            style:
              top: 50%
              right: '-1%'
              transform: 'translate(0%, 0%)'

          #
          # Front Yard
          #
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              bottom: 14%
              left: 37%
              transform: 'translate(0%, 0)'
          - type: state-icon
            icon: 'mdi:walk'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              bottom: 14%
              left: 45%
              transform: 'translate(0%, 0%)'
          - type: state-label
            entity: sensor.living_room_sensor_temperature
            style:
              bottom: 14%
              left: 25%
              color: blue
              transform: 'translate(0%, 0%)'
          
          #
          # Garage
          #
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              bottom: 31%
              left: 26%
              transform: 'translate(0%, 0)'
          - type: state-icon
            icon: 'mdi:walk'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              bottom: 31%
              left: 33%
              transform: 'translate(0%, 0%)'
          - type: state-label
            entity: sensor.living_room_sensor_temperature
            style:
              bottom: 39%
              left: 25%
              color: blue
              transform: 'translate(0%, 0%)'

          #
          # Jocelyns Room
          #
          - type: state-label
            entity: sensor.living_room_sensor_temperature
            style:
              bottom: 26%
              left: 66%
              color: blue
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:walk'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              bottom: 23%
              left: 65%
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              bottom: 29%
              left: 68%
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:spotify'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              bottom: 23%
              left: 72%
              transform: 'translate(0%, 0%)'

          #
          # Logans Room
          #
          - type: state-label
            entity: sensor.logans_room_sensor_temperature
            style:
              bottom: 25%
              right: 5%
              color: blue
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:walk'
            entity: binary_sensor.logans_room_motion
            tap_action:
              action: toggle
            style:
              bottom: 21%
              right: 13%
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.logans_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              bottom: 28%
              right: 9%
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:spotify'
            entity: switch.logans_room_left_plug_switch
            tap_action:
              action: toggle
            style:
              bottom: 21%
              right: 5%
              transform: 'translate(0%, 0%)'

          #
          # Master Bedroom
          #
          - type: state-label
            entity: sensor.living_room_sensor_temperature
            style:
              top: 28%
              left: 40%
              color: blue
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:walk'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              top: 37%
              left: 38%
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              top: 32%
              left: 42%
              transform: 'translate(0%, 0%)'
          - type: state-icon
            icon: 'mdi:spotify'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              top: 37%
              left: 45%
              transform: 'translate(0%, 0%)'

          #
          # Master Closet
          #
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              top: 45%
              left: 25%
              transform: 'translate(0%, 0)'

          #
          # Master Bath
          #
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              top: 31%
              left: 25%
              transform: 'translate(0%, 0)'

          #
          # Laundry Room
          #
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              top: 45%
              left: 34%
              transform: 'translate(0%, 0)'

          #
          # Mud Room
          #
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              top: 43%
              left: 44%
              transform: 'translate(0%, 0)'

          #
          # Bathroom
          #
          - type: state-icon
            icon: 'mdi:lightbulb'
            entity: switch.living_room_right_plug_switch
            tap_action:
              action: toggle
            style:
              top: 52%
              right: 13%
              transform: 'translate(0%, 0)'
        image:
          /local/main-floor-plan.png
  
  - title: Temperature
    path: temperature
    icon: mdi:thermometer
    badges: []
    cards:
      - type: custom:mini-graph-card
        name: Temperature
        icon: mdi:thermometer
        points_per_hour: 2
        entities:
          - entity: sensor.living_room_sensor_temperature
            name: Living Room
            show_fill: false
          - entity: sensor.logans_room_sensor_temperature
            name: Logans Room
            show_fill: false
          - entity: sensor.sun_elevation
            color: orange
            name: Sun elevation
            show_fill: true
            show_line: false
            show_points: false
            show_legend: false
            y_axis: secondary

      - type: custom:mini-graph-card
        name: Humidity
        icon: mdi:water-percent
        points_per_hour: 2
        entities:
          - entity: sensor.living_room_sensor_relative_humidity
            name: Living Room
            show_fill: false
          - entity: sensor.logans_room_sensor_relative_humidity
            name: Logans Room
            show_fill: false

      - type: custom:mini-graph-card
        name: Luminance
        icon: mdi:lightbulb-outline
        points_per_hour: 2
        entities:
          - entity: sensor.living_room_sensor_luminance
            name: Living Room
            show_fill: false
          - entity: sensor.logans_room_sensor_luminance
            name: Logans Room
            show_fill: false

      - type: custom:mini-graph-card
        name: Sun Elevation
        icon: mdi:white-balance-sunny
        points_per_hour: 2
        entities:
          - entity: sensor.sun_elevation
            color: orange
            name: Sun
        # state_map:
        #   - value: "above_horizon"
        #     label: Day
        #   - value: "below_horizon"
        #     label: Night

  - title: Dashboard
    path: dashboard
    icon: mdi:view-dashboard
    badges: []
    cards:
      # - type: horizontal-stack
        # title: Horizonal Stack 1
        # cards:
      - type: vertical-stack
        # title: Vertical Stack 1
        cards:
          - type: custom:weather-card
            entity: weather.openweathermap

          - type: horizontal-stack
            cards:
              - type: button
                name: Home
                icon: mdi:home
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                      entity_id: input_select.occupancy
                      option: Home
                entity: binary_sensor.occupancy_home
                show_state: true
              - type: button
                name: Away
                icon: mdi:home-export-outline
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                      entity_id: input_select.occupancy
                      option: Away
                entity: binary_sensor.occupancy_away
                show_state: true
              - type: button
                name: Sleep
                icon: mdi:sleep
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                      entity_id: input_select.occupancy
                      option: Sleep
                entity: binary_sensor.occupancy_sleep
                show_state: true
              - type: button
                name: Vacation
                icon: mdi:beach
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                      entity_id: input_select.occupancy
                      option: Vacation
                entity: binary_sensor.occupancy_vacation
                show_state: true
          - type: horizontal-stack
            cards:
              - type: button
                name: Garage Door 1
                icon: mdi:garage-variant
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                      entity_id: input_select.occupancy
                      option: Vacation
                entity: binary_sensor.occupancy_vacation
                show_state: true
              - type: button
                name: Garage Door 2
                icon: mdi:garage
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                      entity_id: input_select.occupancy
                      option: Vacation
                entity: binary_sensor.occupancy_vacation
                show_state: true
      - type: vertical-stack
        # title: Vertical Stack 2
        cards:
          - type: entities
            entities:
              - entity: sensor.living_room_climate
              - entity: sensor.kitchen_climate
              - entity: sensor.pantry_climate
              - entity: sensor.laundry_room_climate
              - entity: sensor.mud_room_climate
              - entity: sensor.master_bedroom_climate
              - entity: sensor.master_bathroom_climate
              - entity: sensor.jocelyns_room_climate
              - entity: sensor.logans_room_climate
              - entity: sensor.bathroom_climate
              - entity: sensor.garage_climate
              - entity: sensor.front_yard_climate
              - entity: sensor.back_yard_climate

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                name: Living Room
                icon: mdi:thermometer
                entity: sensor.living_room_sensor_temperature
                graph: line
                detail: 1
              - type: sensor
                name: Master Bedroom
                icon: mdi:thermometer
                entity: sensor.living_room_sensor_temperature
                graph: line
                detail: 1
              - type: sensor
                name: Jocelyns Room
                icon: mdi:thermometer
                entity: sensor.living_room_sensor_temperature
                graph: line
                detail: 1
              - type: sensor
                name: Logans Room
                icon: mdi:thermometer
                entity: sensor.logans_room_sensor_temperature
                graph: line
                detail: 1
          - type: entities
            title: Lights
            icon: mdi:lightbulb
            state_color: true
            entities: 
              - switch.living_room_left_plug_switch
              - switch.living_room_right_plug_switch
              - switch.logans_room_left_plug_switch
              - switch.logans_room_right_plug_switch
          